stages:
  - build
  - deploy

before_script:
  - git config --global http.sslVerify false

get_packer:
  stage: build
  tags: 
  - windows
  artifacts:
    paths:
    - packer.exe
  script:
    - echo $packerVersion
    - $packerFile = "packer_" + $packerVersion + "_windows_amd64.zip"
    - echo $packerFile
    - Write-Output "Fetching packer"
    - Invoke-WebRequest  -Uri ("https://releases.hashicorp.com/packer/" + $packerVersion + "/" + $packerFile) -OutFile $packerFile
    - Expand-Archive $packerFile -DestinationPath .

deploy_windows-10:
  stage: deploy
  tags:
  - windows
  script:
    - Write-Output "Deploying Windows 10"
    - cd windows-10
    - ../packer.exe build -force -var-file variables.json windows-10-pilot.json
