stages:
  - build
  - deploy
  - powercli
  - recompose

before_script:
  - git config --global http.sslVerify false

get_packer:
  stage: build
  tags: 
  - windows
  artifacts:
    paths:
    - packer.exe
  script:
    - Write-Host "Fetching packer"
    - $packerFile = "packer_" + $packerVersion + "_windows_amd64.zip"
    - Invoke-WebRequest -Uri ($packerURL + "/" + $packerVersion + "/" + $packerFile) -OutFile $packerFile
    - Expand-Archive $packerFile -DestinationPath .

deploy_windows-10:
  stage: deploy
  tags:
  - windows
  script:
    - Write-Host "Deploying Windows 10"
    - cd windows-10
    - ../packer.exe build -force windows-10-pilot.json
    - Write-Host "The location is " + $Env:PSModulePath

install_powercli:
  stage: powercli
  tags:
  - windows
  script:
    - Write-Host "Installing NuGet"
    - Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
    - Write-Host "Set the repo installation policy"
    - Set-PSRepository PSGallery -InstallationPolicy Trusted
    - Write-Host "Installing PowerCLI"
    - Install-Module -Name VMware.PowerCLI -Scope CurrentUser -Confirm:$false
    - sleep 60
    - Set-PowerCLIConfiguration -Scope User -ParticipateInCEIP $false -InvalidCertificateAction Ignore -Confirm:$false
    - Write-Host "Importing the helper module"
    - Import-Module VMware.VimAutomation.HorizonView
    - Write-Host "Installing PowerCLI Example scripts"
    - git clone $exampleScriptURL $env:Temp\PowerCLI-Example-Scripts

recompose_pilot_pool:
  stage: recompose
  tags:
  - windows
  script:
    - Write-Host "Connecting to Horizon"
    - $hvServer = Connect-HVServer -Server $cs -User $csUser -Password $csPass -Domain $csDomain
    - $hvServices = $hvserver.ExtensionData
    - $hvServices