stages:
  - build
  - deploy
  - powercli

before_script:
  - git config --global http.sslVerify false

get_packer:
  stage: build
  tags: 
  - windows
  artifacts:
    paths:
    - packer.exe
  script:
    - echo $packerVersion
    - $packerFile = "packer_" + $packerVersion + "_windows_amd64.zip"
    - echo $packerFile
    - Write-Output "Fetching packer"
    - Invoke-WebRequest  -Uri ("https://releases.hashicorp.com/packer/" + $packerVersion + "/" + $packerFile) -OutFile $packerFile
    - Expand-Archive $packerFile -DestinationPath .

deploy_windows-10:
  stage: deploy
  tags:
  - windows
  script:
    - Write-Output "Deploying Windows 10"
    - cd windows-10
    - ../packer.exe build -force -var-file variables.json windows-10-pilot.json

install_vmware_powercli:
  stage: powercli
  tags:
  - windows
  script:
    - Write-Output "Installing NuGet"
    - Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
    - Write-Output "Set the repo installation policy"
    - Set-PSRepository PSGallery -InstallationPolicy Trusted
    - Write-Output "Installing PowerCLI"
    - Install-Module -Name VMware.PowerCLI -Scope CurrentUser -Confirm:$false
    - Get-Module -ListAvailable
    - Write-Output "Importing the helper module"
    - Import-Module VMware.VimAutomation.HorizonView